### ISSUE TITLE
fourier_traj

### ISSUE THREAD

**Issue by kiwiwan** [wangyanhit/dyn_ident_sympy#1]
![screenshot from 2018-10-11 11-02-16](https://user-images.githubusercontent.com/16831845/46778217-5195a800-cd45-11e8-9fc3-e92bdd565a5b.png)
请问一下，上面这段fourier_dq_base的sin和cos项是不是弄反了？

**Comment by wangyanhit** [comment]
应该是弄反了，我写的时候直接copy的忘改了，谢谢提醒
