### ISSUE TITLE
convex result not well

### ISSUE THREAD

**Issue by kiwiwan** [wangyanhit/dyn_ident_sympy#2]
![ols_cf3 0_0](https://user-images.githubusercontent.com/16831845/46851764-3735fa00-ce2b-11e8-8975-969a554df826.png)
                                                       figure 1. OLS result
![wls_cf3 0_0](https://user-images.githubusercontent.com/16831845/46851775-3dc47180-ce2b-11e8-9da7-fc74d53d909e.png)
                                                      figure 2. WLS result
![convex_cf3 0_newconstrain_0](https://user-images.githubusercontent.com/16831845/46851790-4b79f700-ce2b-11e8-946d-37d9886ecd36.png)
                                                     figure 3. convex result

I use this library to identify my ur10 robot in simulation.
The OLS result and WLS result are well.But the convex result so poor.
@wangyanhit ,Could you give me some advice?What's wrong?

**Comment by wangyanhit** [comment]
If there is no constraints on the convex optimization, the results you get from least square and convex optimization should be the same. So my suggestion is first to set the constraints on the inertia parameters to []. If It is right, it means your constraints are not feasible and you can try to play with the constraints to make it right. I also recommend you to fork my repository and push your modeling and results on your Github. In this way, I can see more details.

**Comment by wangyanhit** [comment]
@kiwiwan

**Comment by kiwiwan** [comment]
@wangyanhit ，很感谢你的回答，我之前就试过将约束设为[]，结果也是很差，只稍微会好一点点。我还试过换成CVXOPT求解器，也没什么改善。
我传到Github上了([https://github.com/kiwiwan/ur10_dyn_param_ident/tree/master](https://github.com/kiwiwan/ur10_dyn_param_ident/tree/master))，除了D-H参数不一样，其它的部分我都没改。
我没有用jupyter-notebook,因为在网页里运行时导入你的sdp_opt模块时总是报奇怪的错误： 'module' object has no attribute 'utilities'。应该是numpy或是哪个软件的版本问题。但是在终端执行是可以的。
所以把你的main.ipynb拆开成model.py,excite.py和data_process.py了，你帮我看看data_process.py,里面有数据处理和辨识的部分。
麻烦你了！
方便的话可以加下我微信吗？微信号：w183934863

**Comment by wangyanhit** [comment]
@kiwiwan 你从master clone的代码吗？你试试develop branch的，master那个比较旧一点。我这边是美国，现在晚了，你先试试如果好使或不好使都告诉我一声，如果不好使我明天白天帮你看看。

**Comment by kiwiwan** [comment]
@wangyanhit ，是我弄错了，我之前只是将main.ipynb的约束设为[]。现在我将sdp_opt里的约束全去掉，可以得到和WLS一致的结果。所以H_func生成回归应该没有问题。
现在的问题是，就算只加惯量正定的约束，不加质量和质心约束都会使得结果很差。怎么解决这个问题呢？

**Comment by wangyanhit** [comment]
@kiwiwan 我建议你检查一下你的模型，这里用的是modified DH convention（http://jntuhceh.org/web/tutorials/faculty/873_ic29-2014.pdf），我参考这个建的模型，https://www.universal-robots.com/how-tos-and-faqs/faq/ur-faq/parameters-for-calculations-of-kinematics-and-dynamics-45257/ 我感觉图中这个是机器人零点，和你建模的不太一样，不知道那个对，我用我建的模型得到的结果连OLS和WLS对不太对。
![ur10](https://user-images.githubusercontent.com/24853292/46909778-e34c1380-cf05-11e8-9cfd-9bef16edaf77.png)
![image](https://user-images.githubusercontent.com/24853292/46909789-01b20f00-cf06-11e8-8ad7-fdd908d89174.png)

**Comment by wangyanhit** [comment]
@kiwiwan 我那个链接好像是UR官方给的，怎么和你这个图home position不一致啊

**Comment by wangyanhit** [comment]
在你这个图里，你的参数是没问题的。还有一个问题确认一下，你这个基座的z方向是重力的反方向对吗？

**Comment by wangyanhit** [comment]
我建议你还是用Jupyter notebook 调试起来方便，我用的anaconda。

**Comment by wangyanhit** [comment]
@kiwiwan 我印象中，这个每次生成都不太一样。因为生成这个用了一些随机数，但我试过用这个base parameter乘以H_b 减去所有的参数乘以H，得的结果几乎为零，只剩下一些小数点后好多位的零头

**Comment by wangyanhit** [comment]
https://www.universal-robots.com/how-tos-and-faqs/faq/ur-faq/parameters-for-calculations-of-kinematics-and-dynamics-45257/

**Comment by kiwiwan** [comment]
@wangyanhit ，好的，谢谢你的回答。比较晚了，你先休息吧。我再折腾一下，有问题再请教你。

**Comment by kiwiwan** [comment]
@wangyanhit,  折腾了两天，终于会用anaconda管理环境了。
暂时有一个问题，我用sousa代码生成的base param每次都是一样的，然后我用另一个软件[symoro](https://github.com/symoro/symoro)生成的base param和sousa的生成的是一样的。symoro用的是符号推导的方式。
你的代码生成base param部分采样数只有bary param*2，而sousa的达到10000？我将你代码里的这个采样数改大点（比如4000）就会出现memory error。

**Comment by wangyanhit** [comment]
@kiwiwan 我觉得这个改大点生成的参数可能会更稳定点，这也可能是他每次生成的参数比较一致的原因。但不改大生成的参数也是没问题的，我验证的方法就是我之前说的，看H×parameter-H_b*base_parameter, 如果结果是0,说明这个base_parameter可以完全代表系统的动力学。

**Comment by kiwiwan** [comment]
@wangyanhit,问题解决了，我这边的问题。测得的扭矩数据反号了。我用的vrep仿真，但是vrep里读出来的扭矩和关节执行的力矩符号是相反的。我之前见到过，但是忘了。
今天，我想到用我仿真里ur10模型的惯量数据去预测扭矩，然后发现与测量的扭矩刚好反号了。这样我才分析发现，肯定哪个数据反了。然后关于vrep里扭矩反号的印象猛地想起来。然后再次验证，果真是这样。现在可以出比较好的数据了。
下周用辨识的参数去控制机器人试一下。

**Comment by wangyanhit** [comment]
太好了，如果做control的话最好用New-Euler method，比较高效，适合实时计算，最好用c++。
